apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/imac/Desktop/untitled folder/docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: context
  name: context
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: context
    spec:
      containers:
      - image: context
        name: context
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /home/context/src
          name: context-claim0
      restartPolicy: Always
      volumes:
      - name: context-claim0
        persistentVolumeClaim:
          claimName: context-claim0
status: {}
