apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/imac/Desktop/untitled folder/docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs
  name: ipfs
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ipfs
    spec:
      containers:
      - image: ipfs/go-ipfs:latest
        name: ipfs
        ports:
        - containerPort: 5001
        resources: {}
      restartPolicy: Always
status: {}
